# version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"  # API port
    volumes:
      - ollama:/root/.ollama  # Named volume
      - ./models:/models      # Bind mount
    environment:
      - OLLAMA_ORIGINS=*      # Allow all CORS origins
      - OLLAMA_HOST=0.0.0.0   # Bind to all interfaces
      - OLLAMA_MODELS=/models  # Custom model storage path

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.${ENVIRONMENT}
    container_name: react-frontend.${ENVIRONMENT}
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - ollama

volumes:
  ollama:  # Required declaration for named volume